apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../managed-agents
images:
  - name: zn-datapath-cn-beijing.cr.volces.com/sandbox/veadk-managed-agents-gateway
    newTag: 20260906-skills-03
  - name: zn-datapath-cn-beijing.cr.volces.com/sandbox/ma-server
    newTag: 20260906-agentkit-only-skills-01
  - name: zn-datapath-cn-beijing.cr.volces.com/sandbox/veadk-managed-agents-worker
    newTag: 20260906-scoped-skills-02
